### PR TITLE
Switch internal parser to email-addresses

### PR DESCRIPTION
**Pull request by baudehlo**
This branch switches the internal parser to using email-addresses.

It is currently waiting on a few changes required to the upstream library, and may require a few more tweaks once those go in, as such, tests currently fail so hold off on merging.

### CODE REVIEW

**Comment by baudehlo** [comment]
Because they are tested by email-addresses already so it didn't seem worth
it.

I can put them back in if you want.

**Comment by msimerson** [comment]
> Because they are tested by email-addresses already so it didn't seem worth it.

Ah, right, that makes good sense. :-)

**Comment by msimerson** [comment]
I [see](https://github.com/jackbowman/email-addresses/pulls?q=is%3Apr+is%3Aclosed) that you've got some upstream PRs merged. Is this just waiting on an upstream release now?

**Comment by baudehlo** [comment]
No. The last issue I posted on the repo is still an issue.

Regardless, it doesn't allow us to do SMTPUTF8 in Haraka, but I'll post on
that issue why.

**Comment by msimerson** [comment]
> This now works with my updates to email-addresses

But those are not yet merged/published? And so neither can this, yet?

**Comment by msimerson** [comment]
Never mind. I fixed the lint issues but other issues remain.

**Comment by baudehlo** [comment]
Correct. I'm still waiting on those changes being merged. I ran the tests against a local version. 

When they merge them I'll post on this PR.

**Comment by baudehlo** [comment]
$ npm publish
+ address-rfc2822@2.0.0

**Pull request merged**
