### PR TITLE
Extracting non-latin names (proper check for uppercase)

### LINKED ISSUE #8: Better handling non-latin names
Hey @haraka

Thanks for the module!

By the way I found a little issue with non-latin names.

I suppose the culprit is here - https://github.com/haraka/node-address-rfc2822/blob/master/index.js#L258

When it tries to parse non-latin names it makes them all lowercase, because `\b` doesn't match begging non-ASCII names.

F.e. try to parse `"Имя Фамилия" <name@gmail.com>`

Would you like to accept a PR? I could make it immediately, but not sure if project is still alive so it will be merged at sometime.

### PR DESCRIPTION
**Pull request by vladgolubev**
fixes #8

### CODE REVIEW

**Comment by vladgolubev** [comment]
Travis build fails because of linting.

Missing version constraints in package.json `"eslint": "*"` - so it install latest version which is incompatible with current `grunt-eslint`

**Comment by vladgolubev** [comment]
I disabled linting in .travis.yml as it requires to fix code style in whole project to make ESLint pass. And this is irrelevant to current PR

**Comment by msimerson** [comment]
Hi @vladgolubev , thanks for the PR. Please just remove the 2nd commit, it disables lint checks entirely and that's not what we want. I'll fix the lint issues in another PR.

**Comment by vladgolubev** [comment]
@msimerson Reverted 2nd commit

**Comment by msimerson** [comment]
thanks. I'm fixing the lint issues. Once done, I should be able to pull in this branch and get passing tests.

**Comment by msimerson** [comment]
Hi again @vladgolubev . Thanks for updating. I looked into `is-upper-case`, which is a thin wrapper around `upper-case`, which in turn is still using a regexp, but is doing so using some unicode ranges. While that's a reasonable thing to do, I think it's less than ideal. 

Using native toLowerCase and toUpperCase() has a couple advantages:

1. it's faster
2. doesn't introduce a dependency
3. the native case functions already have unicode support
4. I'd expect the native functions to "get it right" on more languages than the unicode character ranges
5. the code inside that function uses toLowerCase and toUpperCase, so it's unlikely there will ever be mismatches between what is detected and what is transformed.

Your thoughts?

**Comment by vladgolubev** [comment]
@msimerson 

1. Agree!
2. Oh, that's a holy war topic :smiley: I adhere this approach - https://github.com/sindresorhus/ama/issues/10#issuecomment-117766328
3. +
4. I checked that module, yes it uses native `toUpperCase()`. I didn't dig into details, but I see it adds some fallbacks for edge cases, probably because `toUpperCase()` (as a JavaScript itself, TBH) has gaps. I believe author of the module did some research before writing smth such trivial. And `1,326,766` downloads in last month are perhaps not causeless.
5. Also agree. That's the most valid point among above, so I don't mind :+1: 

It's your module after all, so last decision is by you.

**Comment by smfreegard** [comment]
@vladgolubev - the question is, with this change that @msimerson has proposed to your original code; does it still work for your edge-case?

**Comment by vladgolubev** [comment]
@smfreegard yes it is

**Comment by smfreegard** [comment]
Ok +1 then on not introducing additional dependencies unless we have good reason to.

**Comment by msimerson** [comment]
> 4. I checked that module, yes it uses native toUpperCase(). I didn't dig into details, but I see it adds some fallbacks for edge cases, probably because toUpperCase() (as whole JavaScript itself, TBH) has flaws. I believe author of the module did some research before writing smth such trivial. And 1,326,766 downloads in last month are perhaps not causeless.

Excellent point, about the edge cases. But, before worrying about them edge cases, I want them defined and understood. The best tool we have to doing that is our test suite, so if an edge case can be defined, please please open an issue or PR that adds the case(s) to the test suite. Maybe even switch to using upper-case. In any case, having the tests will avoid breaking functionality down the road.

**Pull request closed without merging**
